const authority = [
  {
    "authorityId":1,
    "level":1,
    "parentId":0,
    "description":"企业招聘",
    "childAuthority":[
      {
        "authorityId":8,
        "level":2,
        "parentId":1,
        "description":"企业列表",
        "childAuthority":[
          {
            "authorityId":25,
            "level":3,
            "parentId":8,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":26,
            "level":3,
            "parentId":8,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":27,
            "level":3,
            "parentId":8,
            "description":"删除",
            "childAuthority":null
          }
        ]
      },
      {
        "authorityId":9,
        "level":2,
        "parentId":1,
        "description":"招聘列表",
        "childAuthority":[
          {
            "authorityId":28,
            "level":3,
            "parentId":9,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":29,
            "level":3,
            "parentId":9,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":30,
            "level":3,
            "parentId":9,
            "description":"删除",
            "childAuthority":null
          }
        ]
      },
      {
        "authorityId":10,
        "level":2,
        "parentId":1,
        "description":"招聘类型",
        "childAuthority":[
          {
            "authorityId":31,
            "level":3,
            "parentId":10,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":32,
            "level":3,
            "parentId":10,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":33,
            "level":3,
            "parentId":10,
            "description":"删除",
            "childAuthority":null
          }
        ]
      }
    ]
  },
  {
    "authorityId":2,
    "level":1,
    "parentId":0,
    "description":"用户管理",
    "childAuthority":[
      {
        "authorityId":11,
        "level":2,
        "parentId":2,
        "description":"用户列表",
        "childAuthority":[
          {
            "authorityId":34,
            "level":3,
            "parentId":11,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":35,
            "level":3,
            "parentId":11,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":36,
            "level":3,
            "parentId":11,
            "description":"删除",
            "childAuthority":null
          }
        ]
      }
    ]
  },
  {
    "authorityId":3,
    "level":1,
    "parentId":0,
    "description":"新闻管理",
    "childAuthority":[
      {
        "authorityId":12,
        "level":2,
        "parentId":3,
        "description":"新闻列表",
        "childAuthority":[
          {
            "authorityId":37,
            "level":3,
            "parentId":12,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":38,
            "level":3,
            "parentId":12,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":39,
            "level":3,
            "parentId":12,
            "description":"删除",
            "childAuthority":null
          }
        ]
      }
    ]
  },
  {
    "authorityId":4,
    "level":1,
    "parentId":0,
    "description":"广告管理",
    "childAuthority":[
      {
        "authorityId":13,
        "level":2,
        "parentId":4,
        "description":"网站banner",
        "childAuthority":[
          {
            "authorityId":40,
            "level":3,
            "parentId":13,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":41,
            "level":3,
            "parentId":13,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":42,
            "level":3,
            "parentId":13,
            "description":"删除",
            "childAuthority":null
          }
        ]
      },
      {
        "authorityId":14,
        "level":2,
        "parentId":4,
        "description":"小程序banner",
        "childAuthority":[
          {
            "authorityId":43,
            "level":3,
            "parentId":14,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":44,
            "level":3,
            "parentId":14,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":45,
            "level":3,
            "parentId":14,
            "description":"删除",
            "childAuthority":null
          }
        ]
      },
      {
        "authorityId":15,
        "level":2,
        "parentId":4,
        "description":"首页中部广告",
        "childAuthority":[
          {
            "authorityId":46,
            "level":3,
            "parentId":15,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":47,
            "level":3,
            "parentId":15,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":48,
            "level":3,
            "parentId":15,
            "description":"删除",
            "childAuthority":null
          }
        ]
      },
      {
        "authorityId":16,
        "level":2,
        "parentId":4,
        "description":"首页底部广告",
        "childAuthority":[
          {
            "authorityId":49,
            "level":3,
            "parentId":16,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":50,
            "level":3,
            "parentId":16,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":51,
            "level":3,
            "parentId":16,
            "description":"删除",
            "childAuthority":null
          }
        ]
      }
    ]
  },
  {
    "authorityId":5,
    "level":1,
    "parentId":0,
    "description":"活动管理",
    "childAuthority":[
      {
        "authorityId":17,
        "level":2,
        "parentId":5,
        "description":"活动列表",
        "childAuthority":[
          {
            "authorityId":52,
            "level":3,
            "parentId":17,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":53,
            "level":3,
            "parentId":17,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":54,
            "level":3,
            "parentId":17,
            "description":"删除",
            "childAuthority":null
          }
        ]
      }

    ]
  },
  {
    "authorityId":6,
    "level":1,
    "parentId":0,
    "description":"财务管理",
    "childAuthority":[
      {
        "authorityId":18,
        "level":2,
        "parentId":6,
        "description":"订单列表",
        "childAuthority":[
          {
            "authorityId":55,
            "level":3,
            "parentId":18,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":56,
            "level":3,
            "parentId":18,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":57,
            "level":3,
            "parentId":18,
            "description":"删除",
            "childAuthority":null
          }
        ]
      },
      {
        "authorityId":19,
        "level":2,
        "parentId":6,
        "description":"套餐管理",
        "childAuthority":[
          {
            "authorityId":28,
            "level":3,
            "parentId":19,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":29,
            "level":3,
            "parentId":19,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":30,
            "level":3,
            "parentId":19,
            "description":"删除",
            "childAuthority":null
          }
        ]
      },
      {
        "authorityId":20,
        "level":2,
        "parentId":6,
        "description":"发票管理",
        "childAuthority":[
          {
            "authorityId":31,
            "level":3,
            "parentId":20,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":32,
            "level":3,
            "parentId":20,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":33,
            "level":3,
            "parentId":20,
            "description":"删除",
            "childAuthority":null
          }
        ]
      }
    ]
  },
  {
    "authorityId":7,
    "level":1,
    "parentId":0,
    "description":"系统管理",
    "childAuthority":[
      {
        "authorityId":21,
        "level":2,
        "parentId":7,
        "description":"数据统计",
        "childAuthority":[
          {
            "authorityId":25,
            "level":3,
            "parentId":21,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":26,
            "level":3,
            "parentId":21,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":27,
            "level":3,
            "parentId":21,
            "description":"删除",
            "childAuthority":null
          }
        ]
      },
      {
        "authorityId":22,
        "level":2,
        "parentId":7,
        "description":"账号管理",
        "childAuthority":[
          {
            "authorityId":28,
            "level":3,
            "parentId":22,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":29,
            "level":3,
            "parentId":22,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":30,
            "level":3,
            "parentId":22,
            "description":"删除",
            "childAuthority":null
          }
        ]
      },
      {
        "authorityId":23,
        "level":2,
        "parentId":7,
        "description":"权限管理",
        "childAuthority":[
          {
            "authorityId":31,
            "level":3,
            "parentId":23,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":32,
            "level":3,
            "parentId":23,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":33,
            "level":3,
            "parentId":23,
            "description":"删除",
            "childAuthority":null
          }
        ]
      },
      {
        "authorityId":24,
        "level":2,
        "parentId":7,
        "description":"操作日志",
        "childAuthority":[
          {
            "authorityId":31,
            "level":3,
            "parentId":24,
            "description":"添加",
            "childAuthority":null
          },
          {
            "authorityId":32,
            "level":3,
            "parentId":24,
            "description":"修改",
            "childAuthority":null
          },
          {
            "authorityId":33,
            "level":3,
            "parentId":24,
            "description":"删除",
            "childAuthority":null
          }
        ]
      }
    ]
  }
];

export default authority;
